Fix passkey redirect
datasektionen/logout pull request #1
Opened 2024-10-27 15:46 UTC by adriansalamon

When logging in via passcode, a `fetch` request would be made to `/login/passkey/finish`, which in turn would redirect to the callback URL, resulting in a CORS error.

This fixes this by just updating the session cookie from this request. When the browser then redirects to `/`, the user will then already be logged in and redirected to the callback URL. Also renamed the cookie values to something more unique to logout :)

2024-10-27 17:43 UTC, foodelevator commented
Ah, I had noticed that stuff didn't always work. Though I guess it only worked on the second try when I was already logged in... Nice fix!
I'm kind of inclined to prefer either adding a flag to `LoginUser` saying if it should redirect or not, or adding `redirect: "manual"` to the `fetch` call in `services/passkey/passkey.templ`, since otherwise it seems like `LoginUser` always should be used when logging users in. But idk, maybe that's weird, what do you think @adriansalamon?

2024-10-27 18:00 UTC, foodelevator requested changes
Just some small naming thingies

2024-10-27 18:00 UTC, foodelevator commented on services/user/auth/auth.go
> +func UserCookie(sessionID string) *http.Cookie {
```suggestion
func SessionCookie(sessionID string) *http.Cookie {
```

2024-10-27 18:00 UTC, foodelevator commented on services/user/user.go
> +		http.SetCookie(w, auth.UserCookie(sessionID.String()))
```suggestion
		http.SetCookie(w, auth.SessionCookie(sessionID.String()))
```

2024-10-28 02:25 UTC, adriansalamon commented
> Ah, I had noticed that stuff didn't always work. Though I guess it only worked on the second try when I was already logged in... Nice fix! I'm kind of inclined to prefer either adding a flag to `LoginUser` saying if it should redirect or not, or adding `redirect: "manual"` to the `fetch` call in `services/passkey/passkey.templ`, since otherwise it seems like `LoginUser` always should be used when logging users in. But idk, maybe that's weird, what do you think @adriansalamon?

There is also [`HX-Redirect`](https://htmx.org/headers/hx-redirect/) that we could use?

2024-10-29 15:06 UTC, foodelevator commented
> There is also [`HX-Redirect`](https://htmx.org/headers/hx-redirect/) that we could use?

Unfortunately not, since that request is made with fetch directly (since you need some custom javascript to call `navigator.credentials.get` anyways.

2024-11-04 22:03 UTC, foodelevator approved these changes
Anyways, very nice changes, thanks!

2024-11-04 22:03 UTC, merged